recepcionist_forocoches_node:
  ros__parameters:
    door:
      pose:
        position:
          x: 1.6
          y: 1.9 
        orientation:
          w: 0.0
    party:
      pose:
        position:
          x: 0.80
          y: 4.30
        orientation:
          w: -3.14
    bar:
      pose:
        position:
          x: -1.30
          y: -2.50
        orientation:
          w: -3.14
    navigation:
      tolerance: 0.35
