recepcionist_forocoches_node:
  ros__parameters:
    door:
      pose:
        position:
          x: 7.5
          y: -0.5 
        orientation:
          w: 1.0
    party:
      pose:
        position:
          x: 1.00
          y: 4.30
        orientation:
          w: 1.0
    bar:
      pose:
        position:
          x: 0.10
          y: 6.00
        orientation:
          w: 1.0
